# Generated by Django 6.0.4 on 2026-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Password',
            field=models.CharField(default=121, max_length=6),
            preserve_default=False,
        ),
    ]
